pluginDisplayName: '&7[&eBukkitGames&7]'
worldName: world
maxPlayers: 24
enableKits: true
deleteWorldOnServerBoot: true
saveWorldOnServerShutDown: false
votesNeededToAutostart: 3
deadPlayersCanChat: false
randomWorldTime: false
roundStartWaitTime: 300
graceperiod: 0
playerSpreadRadius: 100
canBuild: true
dropCrates: true
crateItemSpawnChance: 15
spawnCrateSpawnRadius: 30
spawnCrateAmount: 10
minimalCrates: 100
maximalCrates: 200
arenaSize: 300
minimalArenaSize: 30
shrinkSpeedInSeconds: 15
enableScoreboard: true
winner: Player
randomWorldTime: false